[phases.setup]
nixPkgs = ["python310"]  # Use python311 for 3.11

[phases.build]
cmds = ["RUN python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

[start]
cmd = "/opt/venv/bin/python", "-m", "streamlit", "run", "app.py", "--server.port=8080", "--server.address=0.0.0.0"
